/*
Display only 280 characters of a string like the one used in Twitter?

*/

let mtTweets = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem voluptatum fugit delectus cumque incidunt ea eos assumenda recusandae, earum temporibus accusantium quae, doloremque dolor quas! Rerum dicta quod iure nisi! Ad dignissimos ab est. Omnis repellendus vitae perspiciatis nam eaque ducimus repellat non ratione natus doloribus architecto inventore illo, hic tempore excepturi quibusdam nesciunt rerum impedit voluptates necessitatibus officiis delectus. Error praesentium sequi saepe explicabo id voluptatum voluptatibus a possimus odit magnam, ex pariatur animi, modi vero quidem dolor, doloribus dolores quisquam architecto sunt reprehenderit incidunt commodi iusto voluptatem. Voluptatem vero amet corrupti? Ad id animi eveniet exercitationem, dolorem possimus hic consequuntur saepe placeat repellendus velit, cumque illo dolores ea blanditiis sed explicabo, nam suscipit voluptate labore! Itaque repudiandae voluptates provident quo delectus eius. At consequatur harum laboriosam. Officia id facere quibusdam dignissimos et placeat ipsum eius earum quas, exercitationem ad eos velit illum amet laudantium. Praesentium accusamus enim explicabo tenetur facilis amet obcaecati earum illo quam! Dolore sed doloremque nobis facilis aut! Fugiat provident dolorum non ullam voluptates ab, in cupiditate dolores. Architecto, reiciendis blanditiis eius non a laboriosam molestiae exercitationem laborum accusantium sapiente harum enim beatae dolores deserunt, voluptate maiores, tempore est ad dicta. Impedit aut, nulla autem aliquid esse animi quae eveniet exercitationem nobis earum ducimus error numquam qui placeat! Ex ipsam ipsum minima totam quod distinctio! Libero doloremque enim vel ducimus officia qui necessitatibus explicabo ipsum animi voluptas, et iusto ipsam consequatur porro quasi illum ea quas, ex, eaque odio. Similique aspernatur impedit velit, officia, tempore tenetur voluptatum placeat cumque suscipit corporis vero totam mollitia assumenda excepturi voluptates quisquam porro optio? Quos est non cumque pariatur nesciunt, consectetur sit illum aliquam eius doloribus provident quidem repudiandae ex molestias. Dicta magni corrupti, cum quidem eveniet odio perspiciatis quasi dolorem tempora ipsum possimus magnam delectus debitis, in natus!";

let myActualTweet = myTweets.slice(0,280);
console.log(myActualTweet);
console.log(myActualTweet.length);